CREATE DATABASE IF NOT EXISTS airline_aeropuertos;
USE airline_aeropuertos;

CREATE TABLE IF NOT EXISTS aeropuertos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_iata VARCHAR(3) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    latitud DECIMAL(10, 8) NOT NULL,
    longitud DECIMAL(11, 8) NOT NULL,
    zona_horaria VARCHAR(50) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS terminales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    aeropuerto_id INT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    capacidad_pasajeros INT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (aeropuerto_id) REFERENCES aeropuertos(id)
);

CREATE TABLE IF NOT EXISTS pistas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    aeropuerto_id INT NOT NULL,
    numero VARCHAR(10) NOT NULL,
    longitud_metros INT NOT NULL,
    ancho_metros INT NOT NULL,
    superficie VARCHAR(50) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (aeropuerto_id) REFERENCES aeropuertos(id)
); 