version: '3.8'

services:
  app:
    build: .
    ports:
      - "8006:8006"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1092
      - MYSQL_DATABASE=airline_escalas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - VUELOS_SERVICE_URL=http://vuelos-service:8003/api/v1
      - AEROPUERTOS_SERVICE_URL=http://aeropuertos-service:8005/api/v1
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        while ! nc -z mysql 3307; do
          sleep 1
        done &&
        echo 'MySQL is ready!' &&
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8006 --reload
      "

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1092
      - MYSQL_DATABASE=airline_escalas
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1092"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data: 